# Title stuff
  title: Andrea Pasqualini
  description: PhD candidate in Economics
# Dependencies
  markdown: kramdown
  highlighter: rouge

theme: jekyll-theme-cayman
google-analytics: UA-153303214-1
